name: Deploy PR previews

on:
  workflow_dispatch:
    inputs: {}
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with Pelican 🔧
        run: |
          make html

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: output
