name: Deploy PR previews

on:
  workflow_dispatch:
    inputs: {}
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build 🔧
        run: |
          ./generate.sh

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: build
